#pragma once
#include <iostream>
#include <time.h>
#include <stdlib.h>
#include <tchar.h>
#include <Windows.h>
#include <stdio.h>
#include <string>
#include <fcntl.h>
#include <io.h>
#include <aclapi.h>
#include <strsafe.h>
